### ISSUE TITLE
Crash from the start

### ISSUE THREAD

**Issue by marlester-dev** [hakan-krgn/basic-dependency-injection#1]
So I wanted to use this in my spigot 1.20.1 plugin (gradle 8.2.1), shadowed com.github.hakan-krgn.spigot-injection:injection-core:0.1.2.4 and basically did
@Scanner("me.marlester.rfp")
public class ReallyFakePlayers extends JavaPlugin {
    @Override
    public void onEnable() {
        SpigotBootstrap.run(this);
[
, I started up my test server and saw the big error:
```
Error occurred while enabling ReallyFakePlayers v3.0.0.0-1.20.1 (Is it up to date?)
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/TestServers/1.20.1spigot/plugins/ReallyFakePlayers-3.0.0.0-1.20.1.jar
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
        at java.nio.file.Path.of(Path.java:147) ~[?:?]
        at java.nio.file.Paths.get(Paths.java:69) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.basicdi.reflection.ReflectionUtils.findClasses(ReflectionUtils.java:54) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.basicdi.reflection.Reflection.<init>(Reflection.java:28) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.spinjection.utils.ReflectionUtils.createFrom(ReflectionUtils.java:71) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.spinjection.utils.ReflectionUtils.createFrom(ReflectionUtils.java:58) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.spinjection.utils.ReflectionUtils.createFrom(ReflectionUtils.java:48) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.spinjection.utils.ReflectionUtils.createFrom(ReflectionUtils.java:38) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.spinjection.SpigotBootstrap.<init>(SpigotBootstrap.java:73) ~[?:?]
        at me.marlester.rfp.shadowed.com.hakan.spinjection.SpigotBootstrap.run(SpigotBootstrap.java:40) ~[?:?]
        at me.marlester.rfp.ReallyFakePlayers.onEnable(ReallyFakePlayers.java:19) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3832-Spigot-3374045-a94277a]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I decided to report this right away.

**Comment by hakan-krgn** [comment]
Hello, this seems to come from basic-depenedency-injection library. I'll check it out.

**Comment by marlester-dev** [comment]
Ok

**Comment by hakan-krgn** [comment]
Completed. (https://github.com/hakan-krgn/basic-dependency-injection/commit/8c97a491cf53d2792d118152de4485f6ca97ce82)
